//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace IryTech.AdmissionJankari20.Web.NewsAndArticles {
    
    
    public partial class NoticeDetails {
        
        /// <summary>
        /// NoticeTitle control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl NoticeTitle;
        
        /// <summary>
        /// ADMJCommentCount control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::IryTech.AdmissionJankari20.Web.UserControl.CommentCount ADMJCommentCount;
        
        /// <summary>
        /// ADMJTotalViews control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::IryTech.AdmissionJankari20.Web.UserControl.TotalViews ADMJTotalViews;
        
        /// <summary>
        /// ADMJPrint control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::IryTech.AdmissionJankari20.Web.UserControl.Print ADMJPrint;
        
        /// <summary>
        /// UcRating control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::IryTech.AdmissionJankari20.Web.UserControl.UcRatingControl UcRating;
        
        /// <summary>
        /// spnDate control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl spnDate;
        
        /// <summary>
        /// ImgNotice control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Image ImgNotice;
        
        /// <summary>
        /// noticeDesc control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl noticeDesc;
        
        /// <summary>
        /// UCADMJFacebookfan control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::IryTech.AdmissionJankari20.Web.UserControl.ucFacebookfanNewsArticles UCADMJFacebookfan;
        
        /// <summary>
        /// updNoticeMaster control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.UpdatePanel updNoticeMaster;
        
        /// <summary>
        /// UcComment control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::IryTech.AdmissionJankari20.Web.UserControl.UcCommonComment UcComment;
        
        /// <summary>
        /// ucLatestNotice control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::IryTech.AdmissionJankari20.Web.UserControl.LatestNotice ucLatestNotice;
        
        /// <summary>
        /// ucMostviewdNotice control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::IryTech.AdmissionJankari20.Web.UserControl.UcMostViewdNotice ucMostviewdNotice;
        
        /// <summary>
        /// ucMostViewdCollege control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::IryTech.AdmissionJankari20.Web.UserControl.UcMostViewedCollege ucMostViewdCollege;
        
        /// <summary>
        /// ADMJReportAbuse control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::IryTech.AdmissionJankari20.Web.UserControl.ReportAbuse ADMJReportAbuse;
        
        /// <summary>
        /// ADMJForwardEmail control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::IryTech.AdmissionJankari20.Web.UserControl.ForwardFriends ADMJForwardEmail;
    }
}
