//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace IryTech.AdmissionJankari20.Web {
    
    
    public partial class _Default {
        
        /// <summary>
        /// ucCollegeName control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::IryTech.AdmissionJankari20.Web.UserControl.CollegeSearch ucCollegeName;
        
        /// <summary>
        /// ucToRankedCollege control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::IryTech.AdmissionJankari20.Web.UserControl.TopRankedColleges ucToRankedCollege;
        
        /// <summary>
        /// ucBestPrivateCollege control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::IryTech.AdmissionJankari20.Web.UserControl.BestPrivateCollegesList ucBestPrivateCollege;
        
        /// <summary>
        /// ucQuery control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::IryTech.AdmissionJankari20.Web.UserControl.CommonQuickQuery ucQuery;
        
        /// <summary>
        /// ucLatestNews control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::IryTech.AdmissionJankari20.Web.UserControl.ucLatestNews ucLatestNews;
    }
}
