//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace IryTech.AdmissionJankari20.Web.Course {
    
    
    public partial class UniversityDescription {
        
        /// <summary>
        /// CollegeImageHeader control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.ImageMap CollegeImageHeader;
        
        /// <summary>
        /// usUniversityBasicDetails control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::IryTech.AdmissionJankari20.Web.UserControl.UniversityBasicDetails usUniversityBasicDetails;
        
        /// <summary>
        /// usUniversityDescription control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::IryTech.AdmissionJankari20.Web.UserControl.UniversityDescription usUniversityDescription;
        
        /// <summary>
        /// usUniversityContactDetails control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::IryTech.AdmissionJankari20.Web.UserControl.UniversityContactDetails usUniversityContactDetails;
        
        /// <summary>
        /// ucUniversityRealtedCollege control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::IryTech.AdmissionJankari20.Web.UserControl.UcCollegeListRelatedUniversity ucUniversityRealtedCollege;
    }
}
